services:
  # PostgreSQL database service for KeyCloak
  # Store all Keycloak users, realm and clients
  # Must be started before Keycloak service
  # Connected to Keycloak via keycloak-network
  # Data persisted through postgres_data volume
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
       POSTGRES_DB: keycloak
       POSTGRES_USER: keycloak
       POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_data:/var/lib/postgresql/database
    healthcheck:
      test: ["CMD", "pg_isready","-U","keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak-network

  # Keycloak Authentication Server
  # Provides OAuth2/OpenID Connect functionality
  # Depends on Postgres service for data persistance
  # Accessible on post 8080
  # connect to PostgreSQL via keycloak-network
  # configured for development mode with HTTP enabled
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: keycloak
    environment:
       KC_DB: postgres
       KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
       KC_DB_USERNAME: keycloak
       KC_DB_PASSWORD: keycloak_password
       KEYCLOAK_ADMIN: admin
       KEYCLOAK_ADMIN_PASSWORD: admin_password
       KC_HOSTNAME_STRICT: false
       KC_HOSTNAME_STRICT_HTTPS: false
       KC_HTTP_ENABLED: true
    command: 
       - start-dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak-network
  
  # Grafana app where we are going to have SSO
  # Place the Grafana settings file outside
  # use volume mapping to map the settings file to the container instance
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - keycloak-network
    depends_on:
      - keycloak

volumes:
  postgres_data:
    name: keycloak_postgres_data

networks:
  keycloak-network:
    name: keycloak-network
